include: package:lint/strict.yaml

analyzer:
  errors:
    avoid_classes_with_only_static_members: ignore
    avoid_implementing_value_types: ignore
    subtype_of_sealed_class: ignore
    unreachable_from_main: ignore
    use_build_context_synchronously: ignore
  language:
    strict-casts: false

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    avoid_function_literals_in_foreach_calls: false
    document_ignores: false
