name: app_sale_tickets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.12
  dio: ^5.8.0+1
  encrypt: ^5.0.3
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  intl: ^0.20.2
  mailer: ^6.4.1
  mobile_scanner: ^6.0.10
  pdf: ^3.11.3
  provider: ^6.0.0
  qr_flutter: ^4.1.0
  secure_string_compressor: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
